const contTruckPayrate = {
    haulerProjectId:String,
    haulerProjectName:String,
    haulerOrgName: String,
    haulerOrgId: String,
    contractorOrgId: String,
    contractorOrgName: String,
    truck: Number,
    truckId:String,
    truckTypeId: String,
    truckType: String,
    capacity: Number,
    capacityType: String,
    AssignedById: String,
    AssignedByName: String,
    AssignnedByRole: String,
    payRate: {
        payRateId: String,
        chargeType: String,
        charge: Number,
        payRateDescription:String
    },
    isDelete: Boolean,
    isAssigned: Boolean,
    createdAt: Number,
    updatedAt: Number,
}
const actualContTruckPayrate = {
    haulerProjectId:"66448d6c709f0d1aa6c630d5",
    haulerProjectName:"First",
    haulerOrgId: "6634c2160991c5bc59c4d6d6",
    haulerOrgName: "JD Developers",
    contractorOrgId: "66507453822bdc6e3ecf155d",
    contractorOrgName: "Mercer Transportation",
    truck: 1001,
    truckId:"664747a32c3a4fb4f0055e36",
    truckTypeId: "66d1658453c291aba2cd8f2f",
    truckType: "Tandemq",
    capacity: 0,
    capacityType: "CY",
    AssignedById: "6634d6510991c5bc5913d12f",
    AssignedByName: "Hauler Truck boss",
    AssignnedByRole: "Hauler",
    payRate: {
        payRateId: "66d59af8013cd52e1ae6a85c",
        chargeType: "HR",
        charge: 12,
        payRateDescription:""
    },
    isDelete: false,
    isAssigned: false,
    createdAt: 1715947427337,
    updatedAt: 1725882454583,
}
