
const projectMember = {
    projectId: String,
    projectUniqueId: String,
    projectName: String,
    projectCreatedBy: String,
    organizationId: String,
    userId: String,
    firstName: String,
    lastName: String,
    role: String,
    mobileNumber: String,
    countryCode: String,
    countryCodeEmoji: String,
    email: String,
    profileImage: String,
    status: String,
}
const actualProjectMember = {
    projectId: "674ee5fd4c134f7986f0b802",
    projectUniqueId: "tt",
    projectName: "tt",
    projectCreatedBy: "6747ec1aa3f6ce9b1617a4c5",
    organizationId: "67444cf0c35a98e614feef00",
    userId: "6747ec1aa3f6ce9b1617a4c5",
    firstName: "Teet",
    lastName: "New",
    role: "Admin",
    mobileNumber: "9155555444",
    countryCode: "+91",
    countryCodeEmoji: "https://flagcdn.com/w160/in.png",
    email: "testdata@gmail.com",
    profileImage: "",
    status: "Active",
}